poller_phx/lib/poller_phx_web/router.ex
defmodule PollerPhxWeb.Router do
  use PollerPhxWeb, :router

  # valid_user: 2, admin_user

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # add the auth module plug to the browser pipeline
    plug PollerPhxWeb.Plugs.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    # add plugs here, so we can authenticate the user
    plug :fetch_session
    plug PollerPhxWeb.Plugs.Auth
  end

  scope "/", PollerPhxWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/districts", PollerPhxWeb do
    # [:valid_user, :admin_user] are imported automatically when router above is imported, as seen in poller_phx_web.ex
    pipe_through [:browser, :valid_user, :admin_user]

    # get "/", DistrictController, :index
    # get "/new", DistrictController, :new
    # post "/", DistrictController, :create
    # get "/:id/edit", DistrictController, :edit
    # put "/:id", DistrictController, :update
    # delete "/:id", DistrictController, :delete

    resources "/", DistrictController, except: [:show]
    resources "/:district_id/questions", QuestionController, except: [:show]
    resources "/:district_id/questions/:question_id/choices", ChoiceController, except: [:show]
  end

  scope "/auth", PollerPhxWeb do
    pipe_through :browser

    get "/login", AuthController, :new
    post "/login", AuthController, :create
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", PollerPhxWeb.Api do
    # unauthenticated routes
    pipe_through :api

    get "/districts", DistrictController, :index
    get "/districts/:district_id", DistrictController, :show
    get "/districts/:district_id/questions", QuestionController, :index
    get "/questions/:question_id/choices", ChoiceController, :index
  end

  scope "/api", PollerPhxWeb.Api do
    # authenticate routes
    pipe_through [:api, :valid_user]

    put "/districts/:district_id/choices/:choice_id", ChoiceController, :vote
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PollerPhxWeb.Telemetry
    end
  end
end

poller_phx/lib/poller_phx_web/controllers/api/choice_controller.ex
defmodule PollerPhxWeb.Api.ChoiceController do
  use PollerPhxWeb, :controller
  alias PollerDal.Choices

  alias Poller.{PollServer, PollSupervisor}

  def index(conn, %{"question_id" => question_id}) do
    choices = Choices.list_choices_by_question_id(question_id)

    render(conn, "index.json", choices: choices)
  end

  def vote(conn, %{"district_id" => district_id, "choice_id" => choice_id}) do
    district_id = String.to_integer(district_id)
    choice_id = String.to_integer(choice_id)
    start_poll(district_id)
    PollServer.vote(district_id, choice_id)

    send_resp(conn, 204, "")
  end

  defp start_poll(district_id) do
    district_name = PollServer.district_name(district_id)

    case Process.whereis(district_name) do
      nil -> PollSupervisor.start_poll(district_id)
      pid -> pid
    end
  end
end

poller_phx/lib/poller_phx_web/controllers/choice_controller.ex
defmodule PollerPhxWeb.ChoiceController do
  # require Logger
  # Logger.debug("Choices: #{inspect(choices)}")
  use PollerPhxWeb, :controller

  alias PollerDal.Districts
  alias PollerDal.Questions
  alias PollerDal.Choices
  alias PollerDal.Choices.Choice

  def index(conn, %{"district_id" => district_id, "question_id" => question_id}) do
    district = Districts.get_district!(district_id)
    question = Questions.get_question!(question_id)
    choices = Choices.list_choices_by_question_id(question.id)

    render(conn, "index.html", district: district, question: question, choices: choices)
  end

  def new(conn, %{"district_id" => district_id, "question_id" => question_id}) do
    district = Districts.get_district!(district_id)
    question = Questions.get_question!(question_id)
    changeset = Choices.change_choice(%Choice{})

    render(conn, "new.html", changeset: changeset, district: district, question: question)
  end

  def create(conn, %{
        "district_id" => district_id,
        "question_id" => question_id,
        "choice" => choice_params
      }) do
    choice_params = Map.merge(choice_params, %{"question_id" => question_id})

    case Choices.create_choice(choice_params) do
      {:ok, _choice} ->
        conn
        |> put_flash(:info, "Choice created successfully.")
        |> redirect(to: Routes.choice_path(conn, :index, district_id, question_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        question = Questions.get_question!(question_id)
        district = Districts.get_district!(district_id)

        render(conn, "new.html", changeset: changeset, question: question, district: district)
    end
  end

  def edit(conn, %{"id" => id, "district_id" => district_id, "question_id" => question_id}) do
    district = Districts.get_district!(district_id)
    question = Questions.get_question!(question_id)
    questions = Questions.list_questions()
    choice = Choices.get_choice!(id)

    changeset = Choices.change_choice(choice)

    render(conn, "edit.html",
      changeset: changeset,
      district: district,
      question: question,
      choice: choice,
      questions: questions
    )
  end

  def update(conn, %{
        "id" => id,
        "district_id" => district_id,
        "question_id" => question_id,
        "choice" => choice_params
      }) do
    choice_params = Map.merge(choice_params, %{"question_id" => question_id})
    choice = Choices.get_choice!(id)

    case Choices.update_choice(choice, choice_params) do
      {:ok, _choice} ->
        conn
        |> put_flash(:info, "Choice updated successfully.")
        |> redirect(to: Routes.choice_path(conn, :index, district_id, question_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        question = Questions.get_question!(question_id)
        district = Districts.get_district!(district_id)
        questions = Questions.list_questions()

        render(conn, "edit.html",
          changeset: changeset,
          district: district,
          question: question,
          choice: choice,
          questions: questions
        )
    end
  end

  def delete(conn, %{"id" => id, "district_id" => district_id, "question_id" => question_id}) do
    choice = Choices.get_choice!(id)
    {:ok, _choice} = Choices.delete_choice(choice)

    conn
    |> put_flash(:info, "Choice deleted successfully.")
    |> redirect(to: Routes.choice_path(conn, :index, district_id, question_id))
  end
end

poller_phx/lib/poller_phx_web/views/choice_view.ex
defmodule PollerPhxWeb.ChoiceView do
  use PollerPhxWeb, :view

  alias PollerDal.Choices

  defdelegate parties, to: Choices

  defdelegate party_description(id), to: Choices
end

poller_phx/lib/poller_phx_web/templates/choice/edit.html.eex
<h1>Edit Choice</h1>
<%= render "form.html", Map.put(assigns, :action, Routes.choice_path(@conn, :update, @district.id, @question.id, @choice)) %>

poller_phx/lib/poller_phx_web/templates/choice/form.html.eex
<h3>District: <%=@district.name%></h3>
<h3>Question: <%=@question.description%></h3>
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
  <div class="error">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
<%= label f, :description %>
<%= text_input f, :description %>
<%= error_tag f, :description %>
<%= label f, :party %>
<%= select f, :party, parties() %>
<%= error_tag f, :party %>
<div>
  <%= submit "Save", class: "btn" %>
  <%= link "Back", to: Routes.choice_path(@conn, :index, @district.id, @question.id) , class: "btn-white"%>
</div>
<% end %>

poller_phx/lib/poller_phx_web/templates/choice/index.html.eex
<h1>Choices for <%= @question.description %> in <%= @district.name %></h1>
<table>
  <thead>
    <tr>
      <th>Choice</th>
      <th>Party</th>
      <th>Votes</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for choice <- @choices do %>
      <tr>
        <td><%= choice.description %></td>
        <td><%= party_description(choice.party) %></td>
        <td><%= choice.votes %></td>
        <td>
          <%= link to: Routes.choice_path(@conn, :edit, @district.id, @question.id, choice) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link to: Routes.choice_path(@conn, :delete, @district.id, @question.id, choice),
            method: :delete,
            data: [confirm: "Are you sure?"] do  %>
            <i class="fas fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= link "New Choice", to: Routes.choice_path(@conn, :new, @district.id, @question.id), class: "btn" %>
  <%= link "Back", to: Routes.question_path(@conn, :index, @district.id), class: "btn-white" %>
</div>

poller_phx/lib/poller_phx_web/templates/choice/new.html.eex
<h1>New Choice</h1>
<%= render "form.html", Map.put(assigns, :action, Routes.choice_path(@conn, :create, @district.id, @question.id)) %>